name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted # This specifies that the job should run on a self-hosted runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world from the self-hosted runner!

      - name: Run a multi-line script
        run: |
          docker build -t integral .
          docker stop integral
          docker rm integral
          docker run -d -p 8080:8080 --name=integral integral
